import express from 'express';import rateLimit from 'express-rate-limit';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import crypto from 'crypto';import multer from 'multer';import nodemailer from 'nodemailer';import pg from 'pg';
const {Pool}=pg;const app=express();const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false}});const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024}});app.use(express.json({limit:'100kb'}));app.use((req,res,next)=>{const o=process.env.FRONTEND_ORIGIN;if(o)res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});const limiter=rateLimit({windowMs:15*60*1000,max:100});app.use(limiter);
const mail=process.env.GMAIL_USER&&process.env.GMAIL_APP_PASSWORD?nodemailer.createTransport({service:'gmail',auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_APP_PASSWORD}}):null;const hash=v=>crypto.createHash('sha256').update(v).digest('hex');function sign(type,id){return jwt.sign({type,id},process.env.JWT_SECRET,{expiresIn:type==='admin'?'2h':'24h'})}function auth(type){return(req,res,next)=>{try{const h=req.headers.authorization||'';const p=jwt.verify(h.replace(/^Bearer /,''),process.env.JWT_SECRET);if(p.type!==type)throw Error();req.auth=p;next()}catch{res.status(401).json({message:'Unauthorized'})}}}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/register',async(req,res)=>{const{name,email,phone}=req.body;if(!name||!email||!/^[0-9]{10}$/.test(phone||''))return res.status(400).json({message:'Enter valid name, email and 10-digit phone.'});const token=crypto.randomBytes(32).toString('hex');try{const r=await pool.query(`insert into students(name,email,phone,verify_hash,verify_expires,status) values($1,$2,$3,$4,now()+interval '30 minutes','unpaid') on conflict(email) do update set name=excluded.name,phone=excluded.phone,verify_hash=excluded.verify_hash,verify_expires=excluded.verify_expires returning email`,[name,email.toLowerCase(),phone,hash(token)]);if(mail){const url=`${process.env.VERIFY_REDIRECT}${token}`;await mail.sendMail({from:process.env.GMAIL_USER,to:r.rows[0].email,subject:'Verify your Masterclass email',text:`Verify your email here: ${url}`})}return res.json({ok:true})}catch(e){console.error(e);res.status(500).json({message:'Registration failed'})}});
app.get('/api/verify',async(req,res)=>{const t=String(req.query.token||'');const r=await pool.query(`select id from students where verify_hash=$1 and verify_expires>now()`,[hash(t)]);if(!r.rowCount)return res.status(400).json({message:'Verification link expired or invalid.'});await pool.query(`update students set verified=true,verify_hash=null,verify_expires=null where id=$1`,[r.rows[0].id]);res.json({token:sign('student',r.rows[0].id)})});
app.get('/api/payment/qr',async(req,res)=>{const r=await pool.query(`select value,content_type from settings where key='upi_qr'`);if(!r.rowCount)return res.status(404).json({message:'QR not configured.'});res.type(r.rows[0].content_type).send(r.rows[0].value)});
app.post('/api/payment/claim',auth('student'),async(req,res)=>{const utr=String(req.body.utr||'').trim();if(!/^[A-Za-z0-9 -]{4,40}$/.test(utr))return res.status(400).json({message:'Enter a valid UTR/reference number.'});await pool.query(`update students set status='pending',utr=$1,updated_at=now() where id=$2 and verified=true`,[utr,req.auth.id]);res.json({ok:true})});
app.get('/api/student/me',auth('student'),async(req,res)=>{const r=await pool.query(`select name,email,status from students where id=$1`,[req.auth.id]);if(!r.rowCount)return res.status(404).json({message:'Student not found'});res.json({name:r.rows[0].name,email:r.rows[0].email,approved:r.rows[0].status==='approved',status:r.rows[0].status})});
app.post('/api/admin/login',async(req,res)=>{const{email,password}=req.body;if(!email||!password||email.toLowerCase()!==process.env.ADMIN_EMAIL.toLowerCase()||!(await bcrypt.compare(password,process.env.ADMIN_PASSWORD_HASH)))return res.status(401).json({message:'Invalid credentials'});res.json({token:sign('admin','admin')})});app.get('/api/admin/me',auth('admin'),(req,res)=>res.json({ok:true}));
app.get('/api/admin/students',auth('admin'),async(req,res)=>{const r=await pool.query(`select id,name,email,phone,status,utr,created_at from students order by created_at desc`);res.json({students:r.rows})});app.patch('/api/admin/students/:id',auth('admin'),async(req,res)=>{const status=req.body.status;if(!['approved','rejected'].includes(status))return res.status(400).json({message:'Invalid status'});const r=await pool.query(`update students set status=$1,updated_at=now() where id=$2 returning email,name`,[status,req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Student not found'});if(status==='approved'&&mail)await mail.sendMail({from:process.env.GMAIL_USER,to:r.rows[0].email,subject:'Masterclass payment approved',text:`Hi ${r.rows[0].name}, your ₹99 payment has been approved. Your student access is ready.`});res.json({ok:true})});app.post('/api/admin/qr',auth('admin'),upload.single('qr'),async(req,res)=>{if(!req.file||!req.file.mimetype.startsWith('image/'))return res.status(400).json({message:'Upload an image QR.'});await pool.query(`insert into settings(key,value,content_type) values('upi_qr',$1,$2) on conflict(key) do update set value=excluded.value,content_type=excluded.content_type,updated_at=now()`,[req.file.buffer,req.file.mimetype]);res.json({ok:true})});
const port=process.env.PORT||10000;app.listen(port,()=>console.log(`API listening on ${port}`));